% An n-dimensional rotation by angle t on the plane generated by the basis
% elements in dimensions d1 and d2
function R = nRotate(t, d1, d2, n)
    R = eye(n);
    
    R_plane = [cos(t),-sin(t);
               sin(t), cos(t)];
    
    I = [d1,d2];
    
    R(I,I) = R_plane;
end